name: Release

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Call Test Workflow
      id: test
      uses: ./.github/workflows/test.yml

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ needs.test.outputs.artifact }}SynthPointer.dll
