name: Test and Release

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Choco packages
      uses: actions/cache@v3
      with:
        path: ~\AppData\Local\Temp\chocolatey
        key: ${{ runner.os }}-choco-${{ hashFiles('**/*.yml') }}
        restore-keys: |
          ${{ runner.os }}-choco-

    - name: Install dependencies
      run: |
        choco install llvm
        choco install make
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Configure
      run: |
        $env:CC="clang"
        $env:CXX="clang++"
        mkdir build
        cd build
        cmake -G "Unix Makefiles" ..

    - name: Build
      run: |
        cd build
        make

    - name: Test
      run: |
        cd build
        ./tests.exe

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: ./build/

  release:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        path: ./build/

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./build/SynthPointer.dll
