name: Release

on:
  repository_dispatch:
    types: [trigger-release]
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        path: ./build/

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./build/SynthPointer.dll
